version:  '3'
services:
  management-frontend:
    build: './src/management/frontend'
    restart: always

  management-backend:
    build: './src/management/backend'
    restart: always

  management-proxy:
    build: './src/management/proxy'
    restart: always
    ports:
      - "9090:80"

  runner:
    build: './src/runner'
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  infinitedb:
    image: 'lucaspape/infinitedb:1.0.27'
    restart: always
    volumes:
      - ./infinitedb_config:/etc/infinitedb
      - ./infinitedb_data:/var/lib/infinitedb