version:  '3'
services:
  frontend:
    build: './src/frontend'
    restart: always

  backend:
    build: './src/backend'
    restart: always

  yadlb-proxy:
    build: './src/yadlb-proxy'
    restart: always
    ports:
      - "9090:80"

  runner:
    build: './src/runner'
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  infinitedb:
    image: 'lucaspape/infinitedb:1.0.27'
    restart: always
    volumes:
      - ./infinitedb_config:/etc/infinitedb
      - ./infinitedb_data:/var/lib/infinitedb